language: java
sudo: required
jdk:
- openjdk8
services:
- docker
script:
- "./.travis/build.sh"
branches:
  only:
  - master
env:
  global:
  - secure: TNZMTulpvEMZ0SnN83slnV8+segEDXF2pzIIB/9lE4eLrosWMAy9YIzwzSLPYBG6X5wQXZ/tByPXmv8OEodHbQeBkiulh/imUkLyvLOysCNvLt3bXDbbRpapXMji0qX/EQIUwoPm4ytQ1V8lSlEkdTty950J7TaPFr1qLB8ADnTAjg0PTvHtad8XgRKt+LIo56OMeGqDaGHduXhvIKZndbc9Ajo2QReJ0nzT/YLqrXe0JTLFD1QIZ0NHbS450D/wyvcPcd1ywxXuFuUx5/2IXReFzVyW7LBVQQa8SH7UXAJ2zHJn3geIYi5zgp2dsqSyNRYwhh3i4J7oWYx6hg1CigkRvfnI19Lb3pXkbKtUBFqxNZeawA6BdIRuMLgNCbDP9R117FtpI/jGlxUMnvVOXjQUJrrtajt+AdepmCqhUexrQg9/3eZ8ZM0qFMO/oXWlojXFg0bbaogts5k/6PMw3RmNjqNwd9fNqHmZpnubHPgTV87vkmGdUaGCuGaZ8U7nUBSDNm/AWQzkgQ6vGhyZFTt4bf7riBoiBWx5mmCtyr1+5+xrnNgMzGrGJVBBHClwOilWOpNWhlGvUJId0163p0AfYYFVExlmeGL0PxnxGW+QfXfr2lOdkYZocn8ojrMl+crW7Vv+3Dta94V050CjpuOiWxFydA5Xh7ItllAHopM=
  - secure: HjshthiH9YkWIFSKJfsqMglGmwzCXY0aGYlrzjU8gakCQUm8AwB9kEU4aLhUUppSsRoKexTIJrQutApOLjlh0J0ww3h+VqmhinYOzqE/ZRyEbVsLyCsfI35i9k8gDiJAb+udXhw9YNiDcMPJn9Zy/XPPdPeKmujd2CYrVnOYOR9Kv976Uu/+TADKkiyfJdtRcKjoQLJpl9cWmXmi3vJoVnxftmZb+ApmU8Pv0QAWoNrbsCs1GOn1iFeRO0UKYHd72zg6eMJRRV7lqPtCcQ3bEUoFth5W5NVGF5EhVDzT/Of44ZGW5FW/neCAlhgVvskBc0snP5sVYNVSx9TbflEmvdlYPqSH34oZ3bYz9ZcFK3jpH53sTISqJG3Rda6bCTQ471o+f3iTU84Pxx8VjYVj9m0kpzZpJJZxXLkQHLhNVyA10YA/LEMCmuSYoyCiZ6LnmeNYGZ7wM8o8JR29PPdL8Q4fgLLX9af6dxP9QZs8XwRfLwdnXOMiCtDwHF/qyTuaujl1Oz43XMhUrQDlPBlytCfPeys/VohVkxgNuNHShPVjNVtRQtzgNgji6vMnjdCrG3bIkyyufPixOv6nL4KUmySEB6L7QsXJh3bR2HzOiYaOGC0t0opHBiUMC1E4Lf4ZDv4WAyPNPOcvv8fHcupQHKj97nPQCXcsBjvTXR0y4Jc=
