apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: processors.streamzi.io
spec:
  group: streamzi.io
  version: v1
  scope: Namespaced
  names:
    plural: processors
    singular: processor
    kind: Processor
    shortNames:
    - proc