apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: data-sink 
  namespace: myproject
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            imagePullPolicy: IfNotPresent
            image: docker.io/matzew/data-sink
