apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: data-src
spec:
  image: docker.io/matzew/data-src
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: inputchannel

